plays(jimi_hendrix, guitar).
plays(josh_homme, guitar).
plays(josh_homme, piano).
plays(kurt_cobain, guitar).
plays(dave_grohl, guitar).
plays(dave_grohl, drums).
plays(freddie_mercury, piano).
plays(eric_clapton, guitar).
plays(slash, guitar).
plays(b_b_king, guitar).
plays(angus_young, guitar).
plays(john_lennon, guitar).
plays(john_lennon, piano).
plays(paul_mccartney, guitar).
plays(paul_mccartney, piano).
plays(paul_mccartney, bass).
plays(paul_mccartney, drums).
plays(george_harrison, guitar).
plays(ringo_starr, drums).
plays(james_hetfield, guitar).
plays(kirk_hammett, guitar).
plays(robert_trujillo, bass).
plays(lars_ulrich, drums).
plays(tom_morello, guitar).
plays(tom_morello, bass).
plays(tom_morello, piano).
plays(tom_morello, drums).
